name: Android CI

on: [push, pull_request]

jobs:
  assembleRelease:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run:  |
        chmod +x ./gradlew
        sudo bash -c "./gradlew assembleRelease --no-daemon"
    - name: Upload to file.io
      run:  |
        cd ./app/build/outputs/apk/release
        curl -F "file=@app-release-unsigned.apk" https://file.io/?expires=3m
